implement yaml
matrix-org/rust-opa-wasm pull request #32
Opened 2022-07-26 09:24 UTC by kaplanelad

Implementing yaml

functions:
[yaml.is_valid](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-encoding-yamlis_valid)
[yaml.marshal](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-encoding-yamlmarshal)
[yaml.is_valid](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-encoding-yamlunmarshal)

2022-07-26 20:55 UTC, kaplanelad commented
Hey @sandhose, 
Run Clippy ci fails on too many lines in `src/builtins/mod.rs` file. 
should I use `#[deny(clippy::too_many_lines)]` on top of `resolve` function?

2022-07-26 22:31 UTC, sandhose commented
> Run Clippy ci fails on too many lines in `src/builtins/mod.rs` file. 
> 
> should I use `#[deny(clippy::too_many_lines)]` on top of `resolve` function?

Sure, go ahead! I did the same in #18

Note that I'm currently out of office until August 1st, so I'll probably review this PR some time next week

2022-07-27 12:37 UTC, kaplanelad commented
> Note that I'm currently out of office until August 1st, so I'll probably review this PR some time next week

Sure no worries, have fun :)

2022-08-02 15:11 UTC, sandhose requested changes
Looks good overall

Could you please signoff your PR as explained in [`CONTRIBUTING.md`](https://github.com/matrix-org/rust-opa-wasm/blob/main/CONTRIBUTING.md#sign-off)?

2022-08-02 15:11 UTC, sandhose commented on tests/infra-fixtures/test-yaml.rego
> +marshal := yaml.marshal("foo: bar\nnum: 1")
I think a better test would be
```suggestion
marshal := yaml.marshal({"foo": "bar", "num": 1})
```

2022-08-02 20:50 UTC, kaplanelad commented
@sandhose following rebase merge --signoff problems and conflicts, the PR included changes that not related to the current yaml pr. 
i have open a new one 
https://github.com/matrix-org/rust-opa-wasm/pull/44

2022-08-02 20:50 UTC, closed without merging